version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      # - source ~/.bashrc
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
     # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - kubectl config set-cluster  microk8s-cluster --server="https://13.229.146.198:16443/"
      - kubectl config set clusters.microk8s-cluster.certificate-authority-data  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVVEU4RmVsMC8ydkhmYWdyQWh0T0VLYnN1V2FNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNRGt4T1RFeE1UVXhNVm9YRFRNeQpNRGt4TmpFeE1UVXhNVm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1bFUxZVdrVTFhS1p1TWVpQnRXVG9KWWUyV0wzSlhoRmd5Z2MKSVdFQlBvQjhVY2VQOGErNjVFNWhKMm1kNy9HMkhtd3ZaSWVkd2R5VHhKaHlJMkd6SDJhZk9WemRYT1hpUkdrLwpzWWVrbnlNaGFVMWlOVlN3WlZwelprOEc3eTJ3djVSVVpmcUFHMUxLNCtvQWN6MGR5K0MwbDVJQll5T3h0VGFYCjBpM2s1eEp1WWk3Ni8rTkdOczNVNkJBeFVySktIVjJ4OHZNemcybmpadGpYa0IxWlZmZlBSS0MxZDFYZ3BSQTEKZTJCYStjSGJtdW1pVmtvT3FsLytYcEpUaDNtUjN4VHo5VHlzUjZPczI2cnA2YURJek9ieE5GT3htNmhwM3JJNApMMnBsUFJJcm1CY3Z3M3VUT1BTbmJ2TSs1WnZzK2NLMHg2ZklRTnphbVUxU1J5WnJIUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVUFLaUZHb1NEMVhOQ2thcGlQbXZHZXNPSHpBd3dId1lEVlIwakJCZ3dGb0FVQUtpRkdvU0QKMVhOQ2thcGlQbXZHZXNPSHpBd3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBSUdwMEZHZGhkcXU2eGRtQWFvU0lieGRHTjU1eGxYOVVWVWgrWG0wamxnQXg2U2FKNmttYnJuUWlQVmpTCmNOV1hQVmMzMlZrRTRUOW9iaDBpWXQrUDhPbWc3bGMySEszZWZwaUNINmRHeG9MZGFVcmI5MmpFbmZvcTBRdW4KTWx3dDhRUVRTSVZrclpLcHloQjZGR0FvZWxPNTJCMjUzTm1Rb1VFMUtteXZtQm1OSmZOMzU0ak5xQW5LY3QvRwpVM1FENzlhOXBxVWdWa09FOWk3a3N6T3RtNG5kV0hOVllySTVKRGp1Yk13ZENHTUFOYjZ5THdqenRIWFNQVWlHCkNmeElyL2p4SlNwZ3R6M0R1Uk9iaXhNdU9Fc3dlRlUyb1lMY1RBMmd4RkdSdStwSFJ5VFNBRXZ3QUtzN1c4NUIKc0hmaHR0Rkk5MjZJbWdWc1ZWTDBtK2NYMGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      - kubectl config set-credentials admin --token="dU9kN0pFQVA2N3Z5S0hiZFY1ei9mQXZDaG9LT3k5UVI5N1FBWUZ3SHlqTT0K"
      - kubectl config set-context default --cluster=microk8s-cluster --user=admin
      - kubectl config use-context defaultew
      - kubectl apply -f react-deployment.yml